---
title: "Native bee data exploration"
author: "Peter Menzies"
date: "11/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(janitor)
```


```{r}
study_data <- read_csv("data/studyData.csv") %>% 
  clean_names()
```

```{r}
grazing <- read_csv("data/grazingData.csv") %>% 
  clean_names()

```


```{r}
grazing_diversity <- grazing %>% 
  filter(Estimate == "diversity")
```

```{r}
estimates <- read_csv("data/estimateCategories.csv")

est_richness <- estimates %>% 
  filter(Est.Simplified == "richness")

est_diversity <- estimates %>% 
  filter(Est.Reduced == "diversity")
```


```{r}
categories <- read_csv("data/grazingCategories.csv")

grazing$grazing.value

level <- grazing %>% 
  group_by(grazing.level) %>% 
  count()
```

```{r}
value <- grazing %>% 
  filter(!is.na(grazing.value))
```


```{r}
grazing_subset <- grazing %>% 
  filter(grazing.level == "grazed" | grazing.level == "ungrazed")
```

```{r}
grazing_est_count <- grazing %>% 
  group_by(grazing.estimate) %>% 
  count()
```


```{r}
aum <- grazing %>% 
  filter(grazing.estimate == "AUM")
```

```{r}
ecosystem <- 
```

```{r}
eco_counts <- study_data %>% 
  group_by(`Ecosystem class`) %>% 
  count()
```

```{r}
study_subset <- study_data %>% 
  select(unique_id, grazer_species, grazer_status, latitude, longitude, ecosystem_class)
```

```{r}
grazing_join <- grazing %>% 
  left_join(study_subset, by = "unique_id") %>% 
  filter(!is.na(grazing_estimate)) %>% 
  filter(estimate == "diversity") %>% 
  mutate(as.numeric(grazing_estimate)) %>% 
  mutate(as.numeric(estimate)) %>% 
  filter(value < 100)
```

```{r}
ggplot(grazing_join, aes(x = grazing_value, y = value)) +
  geom_point()

```


